
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table table3;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView txtSource;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView txtCode;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label1;

	private global::Gtk.Entry txtKey;

	private global::Gtk.Label label2;

	private global::Gtk.Entry txtIV;

	private global::Gtk.Button button1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("AES加/解密");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table3 = new global::Gtk.Table(((uint)(3)), ((uint)(1)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(10));
		this.table3.ColumnSpacing = ((uint)(20));
		// Container child table3.Gtk.Table+TableChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtSource = new global::Gtk.TextView();
		this.txtSource.CanFocus = true;
		this.txtSource.Name = "txtSource";
		this.txtSource.Justification = ((global::Gtk.Justification)(3));
		this.txtSource.WrapMode = ((global::Gtk.WrapMode)(2));
		this.txtSource.LeftMargin = 10;
		this.txtSource.RightMargin = 10;
		this.GtkScrolledWindow.Add(this.txtSource);
		this.table3.Add(this.GtkScrolledWindow);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3[this.GtkScrolledWindow]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		// Container child table3.Gtk.Table+TableChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.txtCode = new global::Gtk.TextView();
		this.txtCode.CanFocus = true;
		this.txtCode.Name = "txtCode";
		this.txtCode.WrapMode = ((global::Gtk.WrapMode)(2));
		this.txtCode.LeftMargin = 10;
		this.txtCode.RightMargin = 10;
		this.GtkScrolledWindow1.Add(this.txtCode);
		this.table3.Add(this.GtkScrolledWindow1);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3[this.GtkScrolledWindow1]));
		w4.TopAttach = ((uint)(2));
		w4.BottomAttach = ((uint)(3));
		// Container child table3.Gtk.Table+TableChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 10;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Key:");
		this.hbox2.Add(this.label1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.txtKey = new global::Gtk.Entry();
		this.txtKey.CanFocus = true;
		this.txtKey.Name = "txtKey";
		this.txtKey.IsEditable = true;
		this.txtKey.InvisibleChar = '●';
		this.hbox2.Add(this.txtKey);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.txtKey]));
		w6.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("IV:");
		this.hbox2.Add(this.label2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label2]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.txtIV = new global::Gtk.Entry();
		this.txtIV.CanFocus = true;
		this.txtIV.Name = "txtIV";
		this.txtIV.IsEditable = true;
		this.txtIV.InvisibleChar = '●';
		this.hbox2.Add(this.txtIV);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.txtIV]));
		w8.Position = 3;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("加/解密");
		this.hbox2.Add(this.button1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button1]));
		w9.Position = 4;
		w9.Expand = false;
		w9.Fill = false;
		this.table3.Add(this.hbox2);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3[this.hbox2]));
		w10.XPadding = ((uint)(10));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add(this.table3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1001;
		this.DefaultHeight = 531;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler(this.BtnDo_Clicked);
	}
}
