
// This file has been generated by the GUI designer. Do not modify.
namespace Publisher.Windows.Widgets
{
	public partial class IosWidget
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label1;

		private global::Gtk.Entry txtVersion;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label2;

		private global::Gtk.CheckButton cbPublished;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label3;

		private global::Gtk.Entry txtDownloadAddress;

		private global::Gtk.HBox hbox3;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Label label4;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView txtMemo;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Button btnPre;

		private global::Gtk.Button btnNext;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Publisher.Windows.Widgets.IosWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Publisher.Windows.Widgets.IosWidget";
			// Container child Publisher.Windows.Widgets.IosWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("版本号: ");
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.txtVersion = new global::Gtk.Entry ();
			this.txtVersion.CanFocus = true;
			this.txtVersion.Name = "txtVersion";
			this.txtVersion.IsEditable = true;
			this.txtVersion.InvisibleChar = '●';
			this.hbox2.Add (this.txtVersion);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtVersion]));
			w2.Position = 1;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("是否已上线: ");
			this.hbox5.Add (this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.cbPublished = new global::Gtk.CheckButton ();
			this.cbPublished.CanFocus = true;
			this.cbPublished.Name = "cbPublished";
			this.cbPublished.Label = global::Mono.Unix.Catalog.GetString ("选择");
			this.cbPublished.DrawIndicator = true;
			this.cbPublished.UseUnderline = true;
			this.hbox5.Add (this.cbPublished);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.cbPublished]));
			w5.Position = 1;
			this.vbox1.Add (this.hbox5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("安装地址: ");
			this.hbox6.Add (this.label3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label3]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.txtDownloadAddress = new global::Gtk.Entry ();
			this.txtDownloadAddress.CanFocus = true;
			this.txtDownloadAddress.Name = "txtDownloadAddress";
			this.txtDownloadAddress.IsEditable = true;
			this.txtDownloadAddress.InvisibleChar = '●';
			this.hbox6.Add (this.txtDownloadAddress);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.txtDownloadAddress]));
			w8.Position = 1;
			this.vbox1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("更新说明: ");
			this.vbox4.Add (this.label4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label4]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtMemo = new global::Gtk.TextView ();
			this.txtMemo.CanFocus = true;
			this.txtMemo.Name = "txtMemo";
			this.GtkScrolledWindow.Add (this.txtMemo);
			this.vbox4.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow]));
			w12.Position = 1;
			this.hbox3.Add (this.vbox4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox4]));
			w13.Position = 0;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w14.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.btnPre = new global::Gtk.Button ();
			this.btnPre.CanFocus = true;
			this.btnPre.Name = "btnPre";
			this.btnPre.UseUnderline = true;
			this.btnPre.Label = global::Mono.Unix.Catalog.GetString ("上一步");
			this.hbox4.Add (this.btnPre);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnPre]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.btnNext = new global::Gtk.Button ();
			this.btnNext.CanFocus = true;
			this.btnNext.Name = "btnNext";
			this.btnNext.UseUnderline = true;
			this.btnNext.Label = global::Mono.Unix.Catalog.GetString ("下一步");
			this.hbox4.Add (this.btnNext);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnNext]));
			w16.PackType = ((global::Gtk.PackType)(1));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w17.Position = 4;
			w17.Expand = false;
			w17.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
