
// This file has been generated by the GUI designer. Do not modify.
namespace Publisher.Windows
{
	public partial class WinPublisher
	{
		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment gaContainer;

		private global::Gtk.Label labelTitle;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Publisher.Windows.WinPublisher
			this.Name = "Publisher.Windows.WinPublisher";
			this.Title = global::Mono.Unix.Catalog.GetString ("WinPublisher");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(3));
			// Container child Publisher.Windows.WinPublisher.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			this.frame1.BorderWidth = ((uint)(6));
			// Container child frame1.Gtk.Container+ContainerChild
			this.gaContainer = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.gaContainer.Name = "gaContainer";
			this.gaContainer.LeftPadding = ((uint)(12));
			this.gaContainer.RightPadding = ((uint)(12));
			this.gaContainer.BottomPadding = ((uint)(12));
			this.gaContainer.BorderWidth = ((uint)(12));
			this.frame1.Add (this.gaContainer);
			this.labelTitle = new global::Gtk.Label ();
			this.labelTitle.Name = "labelTitle";
			this.labelTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>第一步/共三步</b>");
			this.labelTitle.UseMarkup = true;
			this.frame1.LabelWidget = this.labelTitle;
			this.Add (this.frame1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 889;
			this.DefaultHeight = 422;
			this.Show ();
		}
	}
}
