
// This file has been generated by the GUI designer. Do not modify.
namespace Publisher.Windows.Views
{
	public partial class AndroidWidget
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Publisher.Windows.Views.AndroidWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Publisher.Windows.Views.AndroidWidget";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
